SELECT * FROM hospitality.fact_bookings;
select * from dim_hotels;
select * from dim_date;
select * from dim_rooms;
select * from fact_aggregated_bookings;
select count(*) from  fact_aggregated_bookings;
select count(*) from  fact_bookings;
drop table fact_bookings;

-- KPIS
select sum(revenue_realized) from fact_bookings;
select count(booking_id) from fact_bookings;
select sum(capacity) from fact_aggregated_bookings;
SELECT concat(COUNT(CASE WHEN booking_status = 'cancelled' THEN booking_id END) * 100.0 / COUNT(booking_id),"%") AS Cancelled_Percentage
FROM fact_bookings;
select concat(sum(successful_bookings)*100/sum(capacity),"%") as occupancy from 
 fact_aggregated_bookings as a join fact_bookings as b on a.property_id=b.property_id;
 
 -- sum of revenue by city
 select city,sum(revenue_realized) as revenue from dim_hotels as a join fact_bookings as b on a.property_id=b.property_id
 group by city order by  revenue desc;
 
 -- count of booking_id by booking status
 select count(booking_id),booking_status from fact_bookings group by booking_status order by count(booking_id) desc;
 
 -- sum of revenue_realized and count of booking_id by day_type
 select sum(revenue_realized), count(booking_id),day_type from dim_date as a join fact_bookings as b on a.date=b.check_in_date
 group by day_type;
 
 -- sum of revenue_generated by year
 select sum(revenue_generated),booking_date  from fact_bookings group by booking_date ;
 
 -- sum of revenue_realized by booking platform
 select booking_platform,sum(revenue_realized) as revenue from fact_bookings group by booking_platform order by revenue desc;
 
 -- sum of revenue_realized by room_class
 select room_class,sum(revenue_realized) as revenue from dim_rooms as a join fact_bookings as b on a.room_id=b.room_category
 group by room_class order by revenue desc;
 
 
